name: DeathRewards
version: '${project.version}'
main: me.com.Com
api-version: 1.16
website: Biulay
authors: [ DeathRewards ]
depend:
  - MythicMobs
  - PlaceholderAPI
commands:
  Mdr:
    description: this is one commands.